### ISSUE TITLE
SBEP - part spawner, some lua errors

### ISSUE THREAD

**Issue by viktorkovarik** [spacebuild/sbep#89] opened 2016-06-01 20:52 UTC
ServerLog: [ULX] Trainspot.exe<STEAM_0:0:93575692> used the tool sbep_part_spawn
er on maps/sb_forlorn_sb3_r3.bsp
Trainspot.exe<STEAM_0:0:93575692> used the tool sbep_part_spawner on maps/sb_for
lorn_sb3_r3.bsp

[ERROR] addons/sbep-master/lua/weapons/gmod_tool/stools/sbep_part_spawner.lua:64
: attempt to call method 'ConCommand' (a nil value)
  1. RightClick - addons/sbep-master/lua/weapons/gmod_tool/stools/sbep_part_spaw
ner.lua:64
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:281

It seems that this error occurs when you try to switch between part assembler and spawner using right click - Windows srcds

**Comment by generalwrex** [comment] 2016-06-01 21:30
Thanks for the report! We'll look into it

**Comment by viktorkovarik** [comment] 2016-06-01 21:58
My pleasure! I am happy that you started taking care of it, I was so desperate that I planned to try to fix some big bugs on my own but I've failed :D

**Comment by copperwarrior** [comment] 2016-06-01 23:20
This is caused by TheMerkyShadow's recent fix to make the part spawner switch to the part assembler. Currently the functionality only works on servers, but will be fixed as soon as he can revisit it.

**Comment by TheMerkyShadow** [comment] 2016-06-02 16:33
https://github.com/spacebuild/sbep/pull/91/files

**Comment by X-Coder** [comment] 2016-06-03 01:31
TheMerkyShadow fixed the issue, and we changed it to shift-right for quick toggle between both tools. Workshop version needs to be updated first, before it works with it. Until then you can try the current github repository.

**Closed by X-Coder** 2016-06-03 01:31 UTC
